run: std1 std2 std3 std4 std5 std6 std7 std8 std9

std1:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t1_1.in > t1_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t1_2.in > t1_2.out
std2:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t2_1.in > t2_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t2_2.in > t2_2.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t2_3.in > t2_3.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t2_4.in > t2_4.out
std3:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t3_1.in > t3_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t3_2.in > t3_2.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t3_3.in > t3_3.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t3_4.in > t3_4.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t3_5.in > t3_5.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t3_6.in > t3_6.out
std4:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t4_1.in > t4_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t4_2.in > t4_2.out
std5:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t5_1.in > t5_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t5_2.in > t5_2.out
std6:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t6_1.in > t6_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t6_2.in > t6_2.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t6_3.in > t6_3.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t6_4.in > t6_4.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t6_5.in > t6_5.out
std7:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_1.in > t7_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_2.in > t7_2.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_3.in > t7_3.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_4.in > t7_4.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_5.in > t7_5.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_6.in > t7_6.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_7.in > t7_7.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_8.in > t7_8.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t7_9.in > t7_9.out
std8:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t8_1.in > t8_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t8_2.in > t8_2.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t8_3.in > t8_3.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t8_4.in > t8_4.out
std9:
	java -cp ../build/classes/ ce326.hw1.Interpreter < t9_1.in > t9_1.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t9_2.in > t9_2.out
	java -cp ../build/classes/ ce326.hw1.Interpreter < t9_3.in > t9_3.out
